name: CI

on:
    push:
        branches: ['*']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: npm ci
            - run: npm run test:integration
            - run: npm run test:ci

